name: Unit tests

on:
  push:
    # branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache purescript dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            .spago
            ${{ env.spago_global_cache }}
            output
          key: >-
            ${{ hashFiles('pnpm-lock.yaml') }}-
            ${{ hashFiles('spago.yaml') }}

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.13.2
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT


      - name: Install esbuild
        run: pnpm install -g esbuild purs-backend-es

      - name: Install
        run: pnpm i

      - name: Check formatting
        run: pnpm run check

      - name: Build source
        run: pnpm spago build --pedantic-packages

      - name: Run tests (non-bundled with default esbuild)
        run: pnpm run test

      - name: Run tests (bundled with default esbuild)
        run: pnpm run test:esbuild

      - name: Run tests (bundled with purs-backend-es)
        run: pnpm run test:purs-backend-es
